create user authenticator identified by authPass11;
grant connect, resource to authenticator;
grant unlimited tablespace to authenticator;

create table users (
    id    number generated by default as identity primary key,
    email varchar2(50) not null,
    pass  varchar2(200) not null
);